WITH ROOT_TREE AS (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)
SELECT ii.ITEM_ID, ii.ITEM_NAME
FROM ITEM_INFO ii
JOIN ROOT_TREE rt ON ii.ITEM_ID = rt.ITEM_ID
ORDER BY ITEM_ID ASC;