WITH JT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
)

SELECT c.CART_ID
FROM CART_PRODUCTS c
JOIN JT jt ON jt.CART_ID = c.CART_ID
WHERE c.NAME = "Yogurt"
ORDER BY c.CART_ID ASC;