WITH RECURSIVE ECOLI_RECURSIVE_DATA AS (
    SELECT *, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.*, er.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN ECOLI_RECURSIVE_DATA er
    ON e.PARENT_ID = er.ID
)
SELECT ID
FROM ECOLI_RECURSIVE_DATA
WHERE GENERATION = 3
ORDER BY ID;