WITH JT AS (
    SELECT DISTINCT ITEM_NAME
    FROM ITEM_INFO i
    JOIN ITEM_TREE t ON t.PARENT_ITEM_ID = i.ITEM_ID
)

SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
LEFT OUTER JOIN JT jt ON jt.ITEM_NAME = i.ITEM_NAME
WHERE jT.ITEM_NAME IS NULL
ORDER BY i.ITEM_ID DESC;