WITH DATE_TB AS (
    SELECT DISTINCT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON h.CAR_ID = c.CAR_ID
    AND h.START_DATE <= '2022-11-30'
    AND h.END_DATE >= '2022-11-01'
    WHERE h.CAR_ID IS NULL
    AND c.CAR_TYPE IN ('세단', 'SUV')
),

DISCOUNT_TB AS (
    SELECT dt.CAR_ID, dt.CAR_TYPE, dt.DAILY_FEE, DISCOUNT_RATE
    FROM DATE_TB dt
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
    ON dp.CAR_TYPE = dt.CAR_TYPE
    AND LEFT(dp.DURATION_TYPE, 2) = '30'
)

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE) / 100)) FEE
FROM DISCOUNT_TB
WHERE ROUND(DAILY_FEE * 30 * (1 - (DISCOUNT_RATE) / 100)) >= 500000
AND ROUND(DAILY_FEE * 30 * (1- (DISCOUNT_RATE) / 100)) < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;