WITH JT AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) mf
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, mf FAVORITES
FROM REST_INFO r
JOIN JT jt ON jt.FOOD_TYPE = r.FOOD_TYPE
AND jt.mf = r.FAVORITES
ORDER BY r.FOOD_TYPE DESC;