WITH ECOLI_RATE AS (
    SELECT *,
        NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS RATE
    FROM ECOLI_DATA
)
SELECT ID,
    CASE
        WHEN RATE = 1 THEN 'CRITICAL'
        WHEN RATE = 2 THEN 'HIGH'
        WHEN RATE = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RATE
ORDER BY ID ASC;