SELECT u.USER_ID, u.NICKNAME,
    CONCAT_WS(' ', u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2) '전체주소',
    CONCAT_WS('-', SUBSTR(u.TLNO, 1, 3), SUBSTR(u.TLNO, 4, 4), SUBSTR(u.TLNO, 8, 4)) '전화번호'
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u on u.USER_ID = b.WRITER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY u.USER_ID DESC;