SELECT
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    ui.GENDER AS GENDER,
    COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO ui
JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
    AND ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;