SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH, u.GENDER, COUNT(DISTINCT o.USER_ID) USERS
FROM USER_INFO u
JOIN ONLINE_SALE o ON o.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3