WITH MAX_PRICE_TB AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE,
        RANK() OVER(ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
)
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM MAX_PRICE_TB
WHERE RNK = 1;