SELECT YEAR(o.SALES_DATE) YEAR, MONTH(o.SALES_DATE) MONTH, COUNT(DISTINCT o.USER_ID) PURCHASED_USERS,
ROUND((COUNT(DISTINCT o.USER_ID) / (
    SELECT COUNT(DISTINCT USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)), 1) PURCHASED_RATIO
FROM USER_INFO u
JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
WHERE YEAR(u.JOINED) = '2021'
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY 1 ASC, 2 ASC