WITH MONTH_TB AS (SELECT *, MONTH(DIFFERENTIATION_DATE) MT FROM ECOLI_DATA),

QT_TB AS (
SELECT (CASE
    WHEN MT >= 1 AND MT <= 3 THEN '1Q'
    WHEN MT >= 4 AND MT <= 6 THEN '2Q'
    WHEN MT >= 7 AND MT <= 9 THEN '3Q'
    ELSE '4Q'
END) QUARTER
FROM MONTH_TB
)

SELECT QUARTER, COUNT(QUARTER) ECOLI_COUNT
FROM QT_TB
GROUP BY 1
ORDER BY 1 ASC;