WITH JT AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
)

SELECT p.ID, p.NAME, jt.HOST_ID
FROM PLACES p
JOIN JT jt ON jt.HOST_ID = p.HOST_ID
ORDER BY ID ASC;