WITH JT AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT jt.HISTORY_ID,
(CASE
    WHEN p.DISCOUNT_RATE IS NOT NULL THEN c.DAILY_FEE * (1 - SUBSTRING_INDEX(p.DISCOUNT_RATE, '%', 1) / 100) * jt.DIFF
    ELSE c.DAILY_FEE * jt.DIFF
END) FEE
FROM JT jt
JOIN CAR_RENTAL_COMPANY_CAR c ON c.CAR_ID = jt.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON p.CAR_TYPE = c.CAR_TYPE
AND
(
    (p.DURATION_TYPE = '7일 이상' AND jt.DIFF >= 7 AND jt.DIFF < 30) OR
    (p.DURATION_TYPE = '30일 이상' AND jt.DIFF >= 30 AND jt.DIFF < 90) OR
    (p.DURATION_TYPE = '90일 이상' AND jt.DIFF >= 90)
)
WHERE c.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;