SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    
    UNION ALL
    
    SELECT FLAVOR, TOTAL_ORDER
    FROM JULY
) st
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;