WITH CNT AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) cnt
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING cnt = (
        SELECT COUNT(MEMBER_ID) cnt
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY 1 DESC
        LIMIT 1
    )
)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m ON m.MEMBER_ID = r.MEMBER_ID
JOIN CNT c ON r.MEMBER_ID = c.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;