SELECT ni.ITEM_ID, ni.ITEM_NAME, ni.RARITY
FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.PARENT_ITEM_ID
JOIN ITEM_INFO ni ON it.ITEM_iD = ni.ITEM_ID
WHERE ii.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;