WITH JT AS (
    SELECT CAR_ID, COUNT(*) cnt
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
    AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
)

SELECT MONTH(START_DATE) MONTH, c.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
JOIN JT jt ON jt.CAR_ID = c.CAR_ID
WHERE START_DATE >= '2022-08-01'
AND START_DATE <= '2022-10-31'
AND jt.CNT >= 5
GROUP BY 1, 2
ORDER BY 1 ASC, 2 DESC