WITH MAX_TB AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT
    YEAR(e.DIFFERENTIATION_DATE) YEAR,
    (mt.MAX_SIZE - e.SIZE_OF_COLONY) YEAR_DEV,
    e.ID
FROM ECOLI_DATA e
JOIN MAX_TB mt ON YEAR(e.DIFFERENTIATION_DATE) = mt.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;