SELECT fishsub.ID, fni.FISH_NAME, fishsub.LENGTH
FROM (
    SELECT *,
        RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rnk
    FROM FISH_INFO
) AS fishsub
JOIN FISH_NAME_INFO fni ON fishsub.FISH_TYPE = fni.FISH_TYPE
WHERE rnk = 1
ORDER BY fishsub.ID ASC;