WITH JT AS (
    SELECT FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT f.ID, fn.FISH_NAME, f.LENGTH
FROM FISH_INFO f
JOIN JT jt ON jt.FISH_TYPE = f.FISH_TYPE
AND jt.LENGTH = f.LENGTH
JOIN FISH_NAME_INFO fn ON fn.FISH_TYPE = f.FISH_TYPE
ORDER BY 1 ASC;