WITH JT AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) FILE_PATH
FROM JT jt
JOIN USED_GOODS_FILE f
ON f.BOARD_ID = jt.BOARD_ID
ORDER BY f.FILE_ID DESC;