WITH USED_GOODS_BOARD_RNK AS (
    SELECT *,
        RANK() OVER(ORDER BY VIEWS DESC) AS rnk
    FROM USED_GOODS_BOARD
)

SELECT
    CONCAT('/home/grep/src/', ub.BOARD_ID, '/', uf.FILE_ID, uf.FILE_NAME, uf.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD_RNK ub
JOIN USED_GOODS_FILE uf ON ub.BOARD_ID = uf.BOARD_ID
WHERE ub.rnk = 1
ORDER BY uf.FILE_ID DESC;
