WITH JT AS (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT DISTINCT f.CATEGORY, jt.MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN JT jt ON jt.MAX_PRICE = f.PRICE
WHERE f.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC;